Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:  # Elimina esta sección para provocar la alerta
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
